
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        noticeBoard = new javax.swing.JButton();
        bookAppointment = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        main_menu = new javax.swing.JMenu();
        profile_menu = new javax.swing.JMenuItem();
        logout_menu = new javax.swing.JMenuItem();
        options_menu = new javax.swing.JMenu();
        cpass_menu = new javax.swing.JMenuItem();
        meds_menu = new javax.swing.JMenu();
        unpaid_menu = new javax.swing.JMenuItem();
        billed_menu = new javax.swing.JMenuItem();
        appt_menu = new javax.swing.JMenu();
        planned_menu = new javax.swing.JMenuItem();
        history_menu = new javax.swing.JMenuItem();
        help_menu = new javax.swing.JMenu();
        about_menu = new javax.swing.JMenuItem();
        contact_menu = new javax.swing.JMenuItem();

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu12.setText("jMenu12");

        jMenuItem16.setText("jMenuItem16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        noticeBoard.setText("Notice Board");

        bookAppointment.setText("Book Appointment");
        bookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentActionPerformed(evt);
            }
        });

        main_menu.setText("Main Menu");

        profile_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        profile_menu.setText("Profile");
        profile_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_menuActionPerformed(evt);
            }
        });
        main_menu.add(profile_menu);

        logout_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        logout_menu.setText("Logout");
        logout_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuActionPerformed(evt);
            }
        });
        main_menu.add(logout_menu);

        jMenuBar1.add(main_menu);

        options_menu.setText("Options");

        cpass_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        cpass_menu.setText("Change Password");
        cpass_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpass_menuActionPerformed(evt);
            }
        });
        options_menu.add(cpass_menu);

        jMenuBar1.add(options_menu);

        meds_menu.setText("Medicines");

        unpaid_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        unpaid_menu.setText("Unpaid");
        unpaid_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unpaid_menuActionPerformed(evt);
            }
        });
        meds_menu.add(unpaid_menu);

        billed_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        billed_menu.setText("Billed");
        billed_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billed_menuActionPerformed(evt);
            }
        });
        meds_menu.add(billed_menu);

        jMenuBar1.add(meds_menu);

        appt_menu.setText("Appointments");

        planned_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        planned_menu.setText("Planned");
        planned_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planned_menuActionPerformed(evt);
            }
        });
        appt_menu.add(planned_menu);

        history_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        history_menu.setText("History");
        history_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_menuActionPerformed(evt);
            }
        });
        appt_menu.add(history_menu);

        jMenuBar1.add(appt_menu);

        help_menu.setText("Help");
        help_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help_menuActionPerformed(evt);
            }
        });

        about_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        about_menu.setText("About");
        about_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_menuActionPerformed(evt);
            }
        });
        help_menu.add(about_menu);

        contact_menu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        contact_menu.setText("Contact");
        contact_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_menuActionPerformed(evt);
            }
        });
        help_menu.add(contact_menu);

        jMenuBar1.add(help_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noticeBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(bookAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(noticeBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cpass_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpass_menuActionPerformed
        ChangePassword frm = new ChangePassword();
        frm.setVisible(true);
    }//GEN-LAST:event_cpass_menuActionPerformed

    private void history_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_menuActionPerformed
    // ok
    }//GEN-LAST:event_history_menuActionPerformed

    private void profile_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_menuActionPerformed
    // ok
    }//GEN-LAST:event_profile_menuActionPerformed

    private void help_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_menuActionPerformed
    // ok
    }//GEN-LAST:event_help_menuActionPerformed

    private void about_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_menuActionPerformed
    // ok
    }//GEN-LAST:event_about_menuActionPerformed

    private void billed_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billed_menuActionPerformed
    // ok
    }//GEN-LAST:event_billed_menuActionPerformed

    private void contact_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_menuActionPerformed
    // ok
    }//GEN-LAST:event_contact_menuActionPerformed

    private void bookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentActionPerformed
        Appointment frame = new Appointment();
        frame.setVisible(true);
    }//GEN-LAST:event_bookAppointmentActionPerformed

    private void unpaid_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unpaid_menuActionPerformed
    // ok
    }//GEN-LAST:event_unpaid_menuActionPerformed

    private void planned_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planned_menuActionPerformed
    // ok
    }//GEN-LAST:event_planned_menuActionPerformed

    private void logout_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuActionPerformed
    // ok
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_menu;
    private javax.swing.JMenu appt_menu;
    private javax.swing.JMenuItem billed_menu;
    private javax.swing.JButton bookAppointment;
    private javax.swing.JMenuItem contact_menu;
    private javax.swing.JMenuItem cpass_menu;
    private javax.swing.JMenu help_menu;
    private javax.swing.JMenuItem history_menu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem logout_menu;
    private javax.swing.JMenu main_menu;
    private javax.swing.JMenu meds_menu;
    private javax.swing.JButton noticeBoard;
    private javax.swing.JMenu options_menu;
    private javax.swing.JMenuItem planned_menu;
    private javax.swing.JMenuItem profile_menu;
    private javax.swing.JMenuItem unpaid_menu;
    // End of variables declaration//GEN-END:variables
}
